language: C
compiler: gcc
before_install:
  - sudo apt-get install ragel
  - wget https://github.com/performancecopilot/pcp/archive/master.zip -O /tmp/pcp.zip
  - unzip /tmp/pcp -d /tmp/pcp
  - sudo groupadd -r pcp
  - sudo useradd -c "Performance Co-Pilot" -g pcp -d /var/lib/pcp -M -r -s /usr/sbin/nologin pcp
  - cd /tmp/pcp/pcp-master
  - ./configure --prefix=/usr --libexecdir=/usr/lib --sysconfdir=/etc --localstatedir=/var --with-rcdir=/etc/init.d
  - sudo make
  - sudo make install
  - wget https://github.com/tylertreat/chan/archive/master.zip -O /tmp/chan.zip
  - unzip /tmp/chan -d /tmp/chan
  - cd /tmp/chan/chan-master && ./autogen.sh && autoreconf -f -i && ./configure && sudo make install
  - wget https://github.com/HdrHistogram/HdrHistogram_c/archive/master.zip -O /tmp/HdrHistogram_c.zip
  - unzip /tmp/HdrHistogram_c.zip -d /tmp/HdrHistogram_c
  - cd /tmp/HdrHistogram_c/HdrHistogram_c-master && cmake . && sudo make install
  - sudo ldconfig
script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - make test
