language: C
compiler: gcc
before_install:
  - wget https://github.com/tylertreat/chan/archive/master.zip -O /tmp/chan.zip
  - unzip /tmp/chan -d /tmp/chan
  - ./tmp/chan/chan-master/autogen.sh && ./tmp/chan/chan-master/configure && cd /tmp/chan/chan-master/ && sudo make install
  - wget https://github.com/HdrHistogram/HdrHistogram_c/archive/master.zip -O /tmp/HdrHistogram_c.zip
  - unzip /tmp/HdrHistogram_c.zip -d /tmp/HdrHistogram_c
  - cd /tmp/HdrHistogram_c/HdrHistogram_c-master && cmake . && sudo make install
  - ldconfig
install:
  - make
